version: "3"
services:
         reverseproxy:
                 image: qudus/reverseproxy
                 ports:
                         - 8080:8080
                  restart: always
                  depends_on:
                          - backend-user
                          - backend-feed 
         backend-user:
                 image: qudus/udacity-api-user
                 enviroment:
                         POSTGRESS_USERNAME: $POSTGRESS_USERNAME
                         POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
                         POSTGRESS_DB: $POSTGRESS_DB 
                         POSTGRESS_HOST: $POSTGRESS_HOST 
                         AWS_REGION: $AWS_REGION 
                         AWS_PROFILE: $AWS_PROFILE 
                         AWS_BUCKET: $AWS_BUCKET
                         JWT_SECRET: $JWT_SECRET
                         URL: "http://localhost:8100"
          backend-feed:
                  image: qudus/udacity-api-feed
                  volumes:
                          - $HOME/.aws:/root/.aws
                  enviroment:
                          POSTGRESS_USERNAME: $POSTGRESS_USERNAME
                          POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
                          POSTGRESS_DB: $POSTGRESS_DB 
                          POSTGRESS_HOST: $POSTGRESS_HOST 
                          AWS_REGION: $AWS_REGION 
                          AWS_PROFILE: $AWS_PROFILE 
                          AWS_BUCKET: $AWS_BUCKET
                          JWT_SECRET: $JWT_SECRET
                          URL: "http://localhost:8100"    
          frontend:
                  image: qudus/udacity-frontend
                  ports:
                          - "8100:80"

